# https://github.com/arturbosch/detekt/blob/f59aa94c2571878e654d085db20d0a851c6f0239/detekt-cli/src/main/resources/default-detekt-config.yml

comments:
  active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false